name: note
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.1+1
  get: 4.6.5
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: "Nunito"
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
